name: Commit with Checks 1st

on:
  workflow_dispatch:
  schedule:
    - cron: '10 */4 * * *' 

jobs:
  processing_begin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for Changes
        run: echo "Hello Github!" > activity.txt
    
      - name: Check for uncommitted changes (optional)
        run: git status --porcelain

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git fetch && git pull
          git add .
          git commit -m ":rabbit2: Updated Content on $(date +%d-%b)"
          git push
        env:
          USER_ID: ${{ github.actor_id }}
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}