name: Commit with Checks 2nd

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */4 * * *'

jobs:
  processing_begin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set Github Actions
        uses: gotmax23/set-bot-git-user-action@main
        with:
          global: true
          bot: mahak-actions
          name: "Mahak-2701"

      - name: Check for Changes
        run: rm -rf activity.txt
      
      - name: Run checks
        run: |
          sudo apt update; sudo apt upgrade -y
          uname -a

      - name: Check for uncommitted changes (optional)
        run: git status --porcelain

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Mahak-2701"
          git config --global user.email "Mahak-2701@users.noreply.github.com"
          git fetch && git pull
          git add .
          git commit -m ":rabbit2: Updated Content on #today=$(date +%d-%b).

          Co-Authored-by: mahak-actions[bot] <41898282+mahak-actions[bot]@users.noreply.github.com>"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}

      - name: Inform about skipped commit (optional)
        run: |
          echo "No changes detected to commit. Skipping commit."