name: Commit with Checks 1st

on:
  workflow_dispatch:
  schedule:
    - cron: '10 */4 * * *' 

jobs:
  processing_begin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Github Actions
        uses: gotmax23/set-bot-git-user-action@main
        with:
          global: true
          bot: github-actions
          name: "Mahak's Bot"

      - name: Check for Changes
        run: echo "Hello Github!" > activity.txt
      
      - name: Run checks
        run: |
          sudo apt update; sudo apt upgrade -y
          uname -a

      - name: Check for uncommitted changes (optional)
        run: git status --porcelain

      - name: Commit and push changes (if checks pass)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ format('Refreshed & Removed Stuff (%s)', github.sha) }}  # Use dynamic message with SHA
          commit_user_name: ${{ github.actor }}  # Use triggering user's name
          commit_user_email: ${{ github.actor }}@users.noreply.github.com  # Consistent email format
          commit_options: '-a'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}

      - name: Inform about skipped commit (optional)
        if: ${{ failure() }}  # Run only if previous steps failed
        run: |
          echo "No changes detected to commit. Skipping commit."